name: Publish Package

on:
  release:
   types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.9"
      - name: Build the package
        run: uv build
      - name: Publish the package
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
